// Public trip data only. Booking identifiers and original documents stay in .private/.
window.TRIP = {
  updated: '2026-09-29',
  itineraryVersion: 'word-provisional',
  sources: {
    meiji: {title:'明治神宫官方开放时间', url:'https://www.meijijingu.or.jp/en/opening/'},
    scrambleSquare: {title:'Scramble Square 官方楼层与营业时间', url:'https://shibuya-scramble-square.com/faq/'},
    scrambleSquareView: {title:'12 楼夜景位置与实拍', url:'https://nightscape.tokyo/shibuya/shibuya-scramble-square-12f/'},
    shibuyaSky: {title:'SHIBUYA SKY 官方票务', url:'https://www.shibuya-scramble-square.com/sky/ticket/'},
    unitora: {title:'うに虎本店官网 · 营业时间与地址', url:'https://beyondtsukiji-hd.co.jp/shop/unitora-lunch/'},
    tsukiji: {title:'筑地市场官方营业说明', url:'https://www.tsukiji.or.jp/calendar/'},
    yakitoriOptions: {title:'10/12 烧鸟候选 · 照片、套餐与两人余位', url:'assets/guides/yakitori-oct12/'},
    kyotanba: {title:'银座京丹波 · OMAKASE 套餐与预约', url:'https://omakase.in/r/ju354312'},
    aramaki: {title:'新まき · OMAKASE 预约与店铺资料', url:'https://omakase.in/r/wz508015'},
    takahashi: {title:'高はし · TableCheck 预约日历', url:'https://www.tablecheck.com/ja/shops/yakitoritakahashi/reserve?start_date=2026-10-12&num_people=2'},
    tower: {title:'东京塔官方开放时间', url:'https://ticket.tokyotower.co.jp/'},
    towerLights: {title:'东京塔官方亮灯说明', url:'https://www.tokyotower.co.jp/lightup/index.html'},
    tokyo: {title:'日本桥酒店官方交通说明', url:'https://www.gardenhotels.co.jp/nihonbashi-premier/eng/access/'},
    kyoto: {title:'京都三条 PREMIER 官方交通说明', url:'https://www.gardenhotels.co.jp/kyoto-sanjo-premier/eng/access/'},
    osaka: {title:'大阪酒店官方交通说明', url:'https://www.hankyu-hotel.com/hotel/respire/osaka/access/'},
    nex: {title:'JR 东日本 N’EX 官方说明', url:'https://www.jreast.co.jp/multi/nex/'},
    jr: {title:'JR 西日本路线与车票', url:'https://www.westjr.co.jp/travel-information/en/tickets-passes/route-search/?LANG=en'}
  },
  hotels: [
    {id:'tokyo', city:'东京', zh:'三井花园酒店 日本桥 PREMIER', name:'Mitsui Garden Hotel Nihonbashi Premier Tokyo', in:'2026-10-10', out:'2026-10-13', nights:3, checkin:'15:00', checkout:'12:00', room:'高级双床 · 转角房 · 禁烟', address:'3-4-4 Nihonbashi Muromachi, Chuo-ku, Tokyo, 103-0022 Japan', ja:'東京都中央区日本橋室町3-4-4', access:'与三越前站、新日本桥站相连；东京站日本桥口步行最短约 11 分钟。拖行李时建议预留 15–20 分钟。', source:'tokyo', image:'hotel-tokyo', cancel:'10/6 23:59（酒店当地时间）', note:'按预订单，3 晚以上隔日清扫；额外清扫可向前台询问。', official:'https://www.gardenhotels.co.jp/nihonbashi-premier/eng/'},
    {id:'kyoto', city:'京都', zh:'三井花园酒店 京都三条 PREMIER', name:'Mitsui Garden Hotel Kyoto Sanjo PREMIER', in:'2026-10-13', out:'2026-10-16', nights:3, checkin:'15:00', checkout:'12:00', room:'高级双床 · 两张 120cm 床 · 禁烟', address:'45-1 Hishiya-cho, Nakagyo-ku, Kyoto, 604-8131 Japan', ja:'京都市中京区三条通東洞院東入菱屋町45番1', access:'乌丸御池站 5 号出口步行约 3 分钟。京都站乘地铁乌丸线至乌丸御池；从京都站到酒店规划预留 20–30 分钟，含换乘与步行。', source:'kyoto', image:'hotel-kyoto', cancel:'10/9 23:59（酒店当地时间）', note:'15:00 前到达先询问前台寄存行李，提前入住以当天安排为准。', official:'https://www.gardenhotels.co.jp/kyoto-sanjo-premier/eng/'},
    {id:'osaka', city:'大阪', zh:'阪急大阪龙仕柏酒店', name:'Hotel Hankyu RESPIRE OSAKA', in:'2026-10-16', out:'2026-10-18', nights:2, checkin:'15:00', checkout:'12:00', room:'30 层及以上 · 标准双床 · 禁烟', address:'1-1 Ofukacho, Kita-ku, Osaka, 530-0011 Japan', ja:'大阪府大阪市北区大深町1番1号', access:'JR 大阪站 3 楼连络桥出口步行约 3 分钟；Umekita 地下出口步行约 6 分钟。酒店大堂在 Yodobashi Umeda Tower 9 楼。', source:'osaka', image:'hotel-osaka', cancel:'10/14 23:59（酒店当地时间）', note:'预订单写入住接待时间至次日 05:00。10/18 建议早餐后提前退房，按机场计划出发。', official:'https://www.hankyu-hotel.com/en/hotel/respire/osaka/'}
  ],
  flights: [
    {id:'tokyo', title:'出发 · 旧金山至东京', airline:'日本航空', number:'JL57', from:'SFO', fromCity:'旧金山', to:'NRT', toCity:'东京成田', depart:'2026-10-09', arrive:'2026-10-10', depTime:'13:30', arrTime:'16:30', depZone:'PDT / UTC−7', arrZone:'JST / UTC+9', depTerminal:'国际航站楼 I', arrTerminal:'T2', duration:'11 小时', cabin:'经济舱', baggage:'手提 10kg；托运 2 件，每件 23kg（按预订单）', image:'flight-tokyo', note:'跨越日期变更线，抵达日期为日本时间 10/10。两位同行者在同一份去程预订单中。'},
    {id:'beijing', title:'离境 · 大阪至北京', airline:'中国国际航空', number:'CA928', from:'KIX', fromCity:'大阪关西', to:'PEK', toCity:'北京首都', depart:'2026-10-18', arrive:'2026-10-18', depTime:'14:00', arrTime:'16:30', depZone:'JST / UTC+9', arrZone:'CST / UTC+8', depTerminal:'T1', arrTerminal:'T3', duration:'3 小时 30 分', cabin:'超级经济舱', baggage:'手提 5kg；托运 2 件，每件 23kg（按预订单）', image:'flight-beijing', note:'此份离境预订对应 Ziqing。'},
    {id:'shanghai', title:'离境 · 大阪至上海', airline:'中国东方航空', number:'MU516', from:'KIX', fromCity:'大阪关西', to:'PVG', toCity:'上海浦东', depart:'2026-10-18', arrive:'2026-10-18', depTime:'14:20', arrTime:'16:10', depZone:'JST / UTC+9', arrZone:'CST / UTC+8', depTerminal:'T1', arrTerminal:'T1', duration:'2 小时 50 分', cabin:'经济舱', baggage:'手提 8kg；托运 2 件，每件 23kg（按预订单）', image:'flight-shanghai', note:'此份离境预订对应 Yuting；预订单座位为 42D。'}
  ],
  days: [
    {date:'2026-10-09', city:'飞行', group:'出发', title:'从旧金山出发', subtitle:'一觉醒来，就是东京。', hotel:null, tags:['去程已预订'], route:['SFO 国际航站楼','JL57 飞往东京'], events:[
      {time:'10:30',title:'抵达 SFO，办理值机与托运',status:'建议',type:'交通',detail:'按起飞前 3 小时规划预留。实际值机柜台、截止时间以日本航空通知为准；出发前核对证件、机票与行李。',place:'San Francisco International Airport International Terminal'},
      {time:'13:30',title:'JL57 起飞，目的地东京成田',status:'已预订',type:'航班',detail:'旧金山当地时间 10/9 13:30 起飞；飞行 11 小时，日本当地时间 10/10 16:30 抵达。',flight:'tokyo'}],meals:{lunch:'机场 / 机上用餐',dinner:'机上用餐'},todo:[]},
    {date:'2026-10-10', city:'东京', group:'东京', title:'抵达东京，住进日本桥', subtitle:'包车直接到酒店，放好行李再选晚饭。',hotel:'tokyo',tags:['16:30 抵达成田','包车接机 · 待落实','东京第 1 晚'],route:['成田机场 T2','包车直达','日本桥酒店','附近晚饭'],events:[
      {time:'16:30',title:'抵达成田机场 T2',status:'已预订',type:'航班',detail:'JL57 抵达成田 T2；入境、取行李与海关预计 60–90 分钟。',flight:'tokyo',place:'Narita International Airport Terminal 2'},
      {time:'出关后',title:'包车接机 · 成田 T2 → 日本桥酒店',status:'待预订',type:'交通',detail:'包车直达三井花园酒店日本桥 PREMIER。接机人待确认；车程约 1.5–2 小时。',steps:['完成入境、取行李和海关，进入 T2 到达大厅。','与司机会合（接头位置、联系方式待补）。','向司机确认目的地：三井ガーデンホテル日本橋プレミア，東京都中央区日本橋室町3-4-4。','行李上车后直接前往酒店，到达后办理入住。'],origin:'Narita Airport Terminal 2',place:'Mitsui Garden Hotel Nihonbashi Premier Tokyo',travelMode:'driving'},
      {time:'约 19–20 点',title:'酒店办理入住',status:'预计',type:'住宿',detail:'酒店 15:00 起入住。',hotel:'tokyo'},
      {time:'入住后',title:'晚饭首选 · 日本桥いちり寿喜烧',status:'现场候位',type:'餐饮',detail:'Sukiyaki Ichiri：Walk-in，不接受预约；酒店步行约 8–10 分钟。餐食最后点单 20:00，晚到或排队较长就选附近备选。',options:[
        {name:'日本桥いちり · 寿喜烧',kind:'首选 · Walk-in',walk:'约 8–10 分钟',hours:'11:00–21:00 · 餐食最后点单 20:00',address:'東京都中央区日本橋本町1-1-5 日本橋TNビル 1F',query:'Sukiyaki Ichiri Nihonbashi Tokyo 日本橋本町1-1-5',mapUrl:'https://www.google.com/maps/place/Sukiyaki+Ichiri+Nihonbashi+Tokyo/@35.6853196,139.776342,17z/data=!3m1!4b1!4m6!3m5!1s0x601889004d1c4c01:0xd546648fc9d92bad!8m2!3d35.6853196!4d139.776342!16s%2Fg%2F11lms5_xmp',detail:'现场候位。请使用本町 1-1-5 的新店地址。',sourceUrl:'https://tabelog.com/tokyo/A1302/A130202/13315727/',sourceTitle:'店家发布的食べログ门店资料',status:'现场候位'},
        {name:'7-Eleven · 日本桥室町3丁目店',kind:'便利店 · 最近',walk:'约 1–2 分钟 · 同栋楼 1F',hours:'24 小时营业',address:'東京都中央区日本橋室町3-4-4',query:'セブン-イレブン 日本橋室町3丁目店 東京都中央区日本橋室町3-4-4',detail:'酒店同楼 1F；饭团、便当、三明治、饮料。',sourceUrl:'https://www.e-map.ne.jp/p/yamato01/dtl/0352022021/',sourceTitle:'ヤマト官方取扱店资料',status:'备用'},
        {name:'FamilyMart · 日本桥本町二丁目店',kind:'便利店 · 备用',walk:'约 5–7 分钟',hours:'24 小时营业',address:'東京都中央区日本橋本町二丁目6番7号',query:'ファミリーマート 日本橋本町二丁目店 東京都中央区日本橋本町2-6-7',detail:'便当、饭团、炸鸡、饮料。',sourceUrl:'https://store.family.co.jp/points/59147',sourceTitle:'FamilyMart 官方门店资料',status:'备用'},
        {name:'なか卯 · 日本桥本石町店',kind:'简餐 · 亲子丼 / 乌冬',walk:'约 7–9 分钟',hours:'04:00–次日 03:00 · 03:00–04:00 休息',address:'東京都中央区日本橋本石町3-2-3 日本橋オリーブビル',query:'なか卯 日本橋本石町店 東京都中央区日本橋本石町3-2-3',detail:'亲子丼、乌冬；堂食或外带。',sourceUrl:'https://maps.nakau.co.jp/jp/detail/2555.html',sourceTitle:'なか卯官方门店资料',status:'备用'}
      ]}],meals:{lunch:'机上用餐',dinner:'日本桥いちり寿喜烧 · Walk-in；附近简餐 / 便利店备用'},todo:['落实包车接机']},
    {date:'2026-10-11',city:'东京',group:'东京',title:'明治神宫，原宿逛到涩谷',subtitle:'明治神宫、代代木公园、原宿、表参道与涩谷夜景。',hotel:'tokyo',tags:['预计 07:00 酒店出发','17:30 起涩谷夜景','东京第 2 晚'],route:['原宿早餐','明治神宫','代代木公园','原宿','表参道','Cat Street','涩谷路口 / 八公像','Scramble Square 12F','晚餐','歌舞伎町 / 酒吧（待定）'],events:[
      {time:'07:00–约 07:45',title:'酒店 → 原宿 / 明治神宫前',status:'预计',type:'交通',detail:'地铁全程约 40–50 分钟，含步行和换乘；预计 07:40–07:50 抵达原宿一侧。',steps:['从酒店进入三越前站，乘半藏门线往涩谷方向至表参道。','换乘千代田线往代代木上原方向，1 站到明治神宫前。','从 2 号出口一侧出站，步行至原宿站周边早餐店。'],origin:'Mitsui Garden Hotel Nihonbashi Premier Tokyo 東京都中央区日本橋室町3-4-4',place:'Harajuku Station Tokyo'},
      {time:'约 07:45–08:30',title:'原宿 · 咖啡与早餐',status:'待选',type:'餐饮',detail:'早到可吃 Doutor；猿田彦 08:00 开门。',options:[
        {name:'Doutor Coffee · 原宿店',kind:'最早开门 · 三明治与咖啡',walk:'约 2–4 分钟',origin:'Harajuku Station Tokyo',originLabel:'原宿站',hours:'周日 06:45–21:00 · 早餐套餐至 10:30',address:'東京都渋谷区神宮前1-13-18 第2大英ビル',query:'ドトールコーヒーショップ 原宿店 神宮前1-13-18',detail:'连锁咖啡店，适合到原宿后直接吃一顿简单早餐。',sourceUrl:'https://shop.doutor.co.jp/doutor/spot/detail?code=1010451',sourceTitle:'Doutor 官方门店资料',status:'候选'},
        {name:'猿田彦珈琲 · The Bridge 原宿站店',kind:'优先推荐 · 咖啡早餐',walk:'约 1–3 分钟 · 车站 2F',origin:'Harajuku Station Tokyo',originLabel:'原宿站',hours:'08:00–22:00 · 早餐 08:00–11:00',address:'東京都渋谷区神宮前1-18-20 原宿駅2階',query:'猿田彦珈琲 The Bridge 原宿駅店',detail:'在 JR 原宿站 2F、检票口外；紧邻明治神宫原宿口。若 08:00 吃早餐，08:30 再进入神宫。',sourceUrl:'https://sarutahiko.work/pages/the-bridge-harajyuku',sourceTitle:'猿田彦官方门店与早餐菜单',status:'候选'},
        {name:'パンとエスプレッソと · 表参道',kind:'面包与咖啡 · 表参道备选',walk:'约 5 分钟 · A2 出口',origin:'Omotesando Station Tokyo',originLabel:'表参道站',hours:'08:00–19:00 · 不定休',address:'東京都渋谷区神宮前3-4-9',query:'パンとエスプレッソと 表参道 神宮前3-4-9',detail:'想吃面包可选这家。距原宿站约 15–20 分钟步行；早餐会增加往返路程，也可留到逛表参道时吃。',sourceUrl:'https://bread-espresso.jp/shop/omotesando.html',sourceTitle:'店铺官网 · 营业时间与菜单',status:'候选'}
      ]},
      {time:'约 08:30–11:00',title:'明治神宫 + 代代木公园',status:'预计',type:'景点',detail:'08:30–10:00 明治神宫参拜、散步，含参道往返。之后从原宿口出，步行约 5–10 分钟至代代木公园原宿门；公园散步至约 10:45，再步行回原宿商圈。',places:['Meiji Jingu Tokyo','Yoyogi Park Harajuku Gate Tokyo'],source:'meiji'},
      {time:'11:00–约 12:00',title:'原宿 · 购物',status:'预计',type:'游逛',detail:'11:00 起逛原宿、竹下通与明治神宫前周边店铺。',places:['Harajuku Tokyo','Takeshita Street Harajuku Tokyo','Meiji Jingumae Station Tokyo']},
      {time:'12:00–13:15',title:'午餐 · 原宿 / 表参道',status:'待定',type:'餐饮',detail:'餐厅待定。',options:[
        {name:'KATSU プリポー · HARAKADO 原宿店',kind:'优先推荐 · 品牌猪肉炸猪排',walk:'约 1–3 分钟 · 4 / 7 号出口至大楼',origin:'Meiji Jingumae Station Tokyo',originLabel:'明治神宫前站',hours:'午餐 11:00–16:00 · 套餐最后点单 14:30 · 无固定休息日',address:'東京都渋谷区神宮前6-31-21 東急プラザ原宿ハラカド5F 506',query:'PRETTY PORK FACTORY & KATSU プリポー 原宿 ハラカド',detail:'在 HARAKADO 5F，沿表参道主街即可到达，上楼约 3–5 分钟。特选炸猪排套餐 ¥3,300、菲力炸猪排套餐 ¥3,600；含米饭、汤和配菜。店名全称 PRETTY PORK FACTORY & KATSU プリポー。',sourceUrl:'https://prettyporkfactory.com/harajuku/',sourceTitle:'原宿店官方菜单',status:'候选'},
        {name:'AFURI · 原宿店',kind:'拉面 · 原宿站旁',walk:'约 3–5 分钟 · 竹下口一侧',origin:'Harajuku Station Tokyo',originLabel:'原宿站',hours:'10:00–23:00 · 年中无休 · 汤售完可能提前结束',address:'東京都渋谷区千駄ヶ谷3-63-1 グランデフォレスタ1F',query:'AFURI 原宿 千駄ヶ谷3-63-1',detail:'若中午仍在原宿站、竹下通附近，可选这家拉面。门店仅接受无现金支付。',sourceUrl:'https://afuri.com/findus/',sourceTitle:'AFURI 官方门店资料',status:'候选'},
        {name:'やさい家めい · 表参道 Hills 店',kind:'日式御膳 · 商场楼内',walk:'约 5 分钟至商场 · 另计上楼',origin:'Omotesando Station Tokyo',originLabel:'表参道站',hours:'周日午餐 11:00–16:00 · 最后点单 15:30',address:'東京都渋谷区神宮前4-12-10 表参道ヒルズ本館3F',query:'やさい家めい 表参道ヒルズ店 神宮前4-12-10',detail:'在表参道 Hills 本馆 3F，若已逛到这栋商场，可直接上楼。以蔬菜、发酵料理和日式御膳为主；周末菜单见官网。',sourceUrl:'https://yasaiya-mei.com/1647/',sourceTitle:'店铺官网 · 周末午餐菜单',status:'候选'}
      ]},
      {time:'13:15–16:30',title:'表参道 · 购物与咖啡',status:'预计',type:'游逛',detail:'午餐后继续逛表参道、原宿周边的小店，喝咖啡、休息。原宿站到表参道站纯步行约 15–20 分钟。',places:['Omotesando Tokyo','Harajuku Tokyo']},
      {time:'16:30–17:30',title:'表参道 → Cat Street → 涩谷',status:'预计',type:'交通',detail:'沿 Cat Street 边走边逛，约 17:30 到涩谷路口。纯步行约 25–35 分钟，预留 1 小时。',origin:'Omotesando Hills Tokyo',place:'Shibuya Scramble Crossing Tokyo',travelMode:'walking',places:['Cat Street Shibuya','Shibuya Scramble Crossing Tokyo']},
      {time:'17:30–18:00',title:'涩谷路口与忠犬八公像 · 打卡',status:'预计',type:'景点',detail:'拍十字路口夜景，再去涩谷站八公口旁的忠犬八公像；两处步行约 2–3 分钟。',places:['Shibuya Scramble Crossing Tokyo','Hachiko Memorial Statue Shibuya Tokyo']},
      {time:'18:00–18:40',title:'Shibuya Scramble Square · 12 楼夜景',status:'预计',type:'景点',detail:'从八公像步行到大楼、上 12 楼约 10–15 分钟。餐厅层公共窗边可俯瞰涩谷路口，免费，无需预约；留约 20–25 分钟拍照。餐厅层营业 11:00–23:00。',place:'Shibuya Scramble Square Tokyo 渋谷2-24-12',source:'scrambleSquare',extraSource:'scrambleSquareView'},
      {time:'暂留 18:45–20:45',title:'寿司 + 酒肴 omakase',status:'待定',type:'餐饮',detail:'暂留 2 小时用餐；餐厅、到店交通和实际预约时间待定。'},
      {time:'约 20:45–21:20 · 可选',title:'涩谷 → 新宿歌舞伎町',status:'待定',type:'交通',detail:'若晚餐在涩谷：JR 山手线到新宿，再步行至歌舞伎町，全程约 25–35 分钟。',origin:'Shibuya Station Tokyo',place:'Kabukicho Shinjuku Tokyo'},
      {time:'约 21:20–22:00 · 可选',title:'歌舞伎町 / 酒吧',status:'待定',type:'游逛',detail:'候选：新宿歌舞伎町、Golden Gai。',places:['Kabukicho Shinjuku Tokyo','Shinjuku Golden Gai Tokyo']},
      {time:'晚饭后 / 酒吧后',title:'返回日本桥酒店',status:'预计',type:'交通',detail:'涩谷出发：银座线直达三越前，含步行约 35–45 分钟。若去歌舞伎町：步行至新宿三丁目，丸之内线到赤坂见附换银座线至三越前，全程约 45–55 分钟。',origin:'Shibuya Station Tokyo',place:'Mitsui Garden Hotel Nihonbashi Premier Tokyo 東京都中央区日本橋室町3-4-4'}],meals:{breakfast:'原宿咖啡早餐 · Doutor / 猿田彦待选',lunch:'原宿 / 表参道附近 · 待定',dinner:'寿司 + 酒肴 omakase · 待预约'},todo:['确定午餐和晚餐餐厅']},
    {date:'2026-10-12',city:'东京',group:'东京',title:'筑地海胆饭，东京经典一日',subtitle:'筑地、浅草、银座，烧鸟晚餐与东京塔夜景。',hotel:'tokyo',tags:['07:00 酒店出发','09:00 筑地出发','东京第 3 晚'],route:['筑地场外市场','浅草','银座','酒店放东西（可选）','京丹波 19:30','东京塔'],events:[
      {time:'07:00 出发',title:'酒店 → 筑地场外市场',status:'预计',type:'交通',detail:'出租车约 10–20 分钟；地铁全程约 25–35 分钟，预计 07:30–07:40 到うに虎。',steps:['步行约 8–10 分钟至日本桥站，乘都营浅草线往西马込 / 羽田机场方向，2 站到东银座。','东银座 5 / 6 号出口，步行约 5–8 分钟到市场及うに虎。'],origin:'Mitsui Garden Hotel Nihonbashi Premier Tokyo 東京都中央区日本橋室町3-4-4',place:'うに虎 本店 東京都中央区築地4-10-5'},
      {time:'约 07:30–09:00',title:'うに虎海胆饭 → 筑地场外市场',status:'拟定',type:'餐饮',detail:'先吃海胆饭，再逛市场。Unitora Nakadori：官网现称うに虎本店，07:00–17:00，无固定休息日。地址：東京都中央区築地4-10-5 MIHIROビル1F。10/12 为假日，部分市场店铺休息。',places:['うに虎 本店 東京都中央区築地4-10-5','Tsukiji Outer Market Tokyo'],source:'unitora',extraSource:'tsukiji'},
      {time:'09:00 出发',title:'筑地 → 浅草',status:'预计',type:'交通',detail:'步行至东银座，乘都营浅草线往押上方向直达浅草，全程约 30–40 分钟，预计 09:30–09:40 抵达。',steps:['筑地场外市场步行至东银座站。','乘都营浅草线往押上方向，到浅草站下车。','步行至浅草文化观光中心，开始游逛。'],origin:'Tsukiji Outer Market Tokyo',place:'Asakusa Culture Tourist Information Center Tokyo'},
      {time:'约 09:40–13:00',title:'浅草寺周边 · 景点与小吃',status:'预计',type:'景点',detail:'浅草文化观光中心 → 雷门 → 仲见世街 → 宝藏门 → 五重塔 → 浅草寺 → 浅草神社。抹茶店和小吃以我的 Google Maps 收藏为准。观光中心 09:00 开门；隅田川边拍晴空塔可留约 20–30 分钟。',places:['浅草文化观光中心 Asakusa Culture Tourist Information Center Tokyo','雷门 Kaminarimon Tokyo','仲见世街 Nakamise Shopping Street Tokyo','宝藏门 Hozomon Sensoji Tokyo','浅草寺五重塔 Sensoji Five Story Pagoda Tokyo','浅草寺 Sensoji Tokyo','浅草神社 Asakusa Shrine Tokyo','隅田公园 Sumida Park Asakusa Tokyo'],guides:[{title:'浅草景点路线图',path:'assets/guides/asakusa-sights.png',alt:'用户提供的浅草景点攻略图，标注雷门、仲见世街、宝藏门、五重塔、浅草寺和浅草神社，以及周边购物点'},{title:'浅草小吃攻略图',path:'assets/guides/asakusa-route.jpg',alt:'用户提供的浅草附近步行攻略地图，从浅草文化观光中心出发，标有浅草寺及沿途抹茶店、小吃店'}]},
      {time:'约 13:00 出发',title:'浅草 → 银座',status:'预计',type:'交通',detail:'银座线往涩谷方向直达银座，全程约 30–40 分钟。',origin:'Asakusa Station Tokyo Metro Ginza Line',place:'Ginza Tokyo'},
      {time:'约 13:40 起 · 逛至傍晚',title:'银座 · 购物与咖啡',status:'拟定',type:'购物',detail:'LOFT、伊东屋、无印良品、UNIQLO；其他候选店铺见攻略图和地点清单。晚餐前可回酒店放东西或直接前往京丹波。',places:['银座 LOFT Ginza Loft Tokyo','银座伊东屋 Ginza Itoya Tokyo','无印良品 银座店 MUJI Ginza Tokyo','UNIQLO 银座店 UNIQLO Ginza Tokyo','Bic Camera 有乐町店 Bic Camera Yurakucho Tokyo','LUMINE 有乐町 Lumine Yurakucho Tokyo','三丽鸥世界 银座店 Sanrio World Ginza Tokyo','松本清 银座 FLAG 店 Matsumoto Kiyoshi Ginza Flag Tokyo','Apple 银座店 Apple Ginza Tokyo','松屋银座 Matsuya Ginza Tokyo','银座三越 Ginza Mitsukoshi Tokyo','Dover Street Market Ginza Tokyo','GINZA SIX Tokyo','鬼冢虎 银座店 Onitsuka Tiger Ginza Tokyo','唐吉诃德 银座本馆 Don Quijote Ginza Honkan Tokyo'],guide:{title:'银座购物攻略图',path:'assets/guides/ginza-shopping.jpg',alt:'用户提供的银座购物地图，标注 LOFT、伊东屋、无印良品、UNIQLO、百货、杂货、药妆及品牌店'}},
      {time:'晚餐前 · 两种走法',title:'回酒店放东西 / 直接前往京丹波',status:'可选',type:'交通',detail:'回酒店：银座 → 日本桥酒店，地铁约 20–30 分钟；酒店 → 京丹波，地铁约 25–35 分钟，出租车约 15–25 分钟。直接到店：银座附近步行约 5–20 分钟，视最后一家店位置而定。以上为估算。',steps:['回酒店：约 18:00 离开银座，乘银座线往浅草方向到三越前，回酒店放东西。','约 18:35–18:40 从酒店出发，三越前乘银座线往涩谷方向到银座，步行到银座グランベルスクエア 2F 京丹波。','直接到店：购物后步行前往，约 19:15 到店。'],origin:'Mitsui Garden Hotel Nihonbashi Premier Tokyo 東京都中央区日本橋室町3-4-4',place:'銀座やきとり 京丹波 東京都中央区銀座7-2-18 銀座グランベルスクエア201',places:['Mitsui Garden Hotel Nihonbashi Premier Tokyo 東京都中央区日本橋室町3-4-4','銀座やきとり 京丹波 東京都中央区銀座7-2-18 銀座グランベルスクエア201'],source:'tokyo',extraSource:'kyotanba'},
      {time:'19:30–约 21:30',title:'银座京丹波 · 烧鸟晚餐',status:'已预订',type:'餐饮',detail:'10/12 19:30，两人吧台，滞留时间 2 小时。高坂鸡季节限定套餐。地址：東京都中央区銀座7-2-18 銀座グランベルスクエア201。',confirmation:{image:'restaurant-kyotanba',title:'京丹波 · 10/12 19:30 两人预约确认',price:'高坂鸡季节限定套餐 ¥22,000 / 人（含税），另加 10% 服务费。两人餐费加服务费约 ¥48,400，OMAKASE 预约费共 ¥780；酒水另计。',note:'到店出示 OMAKASE 预约记录或确认邮件。10/9 起取消收套餐费 50%，10/12 当天收 100%；预约费不可退。'},place:'銀座やきとり 京丹波 東京都中央区銀座7-2-18 銀座グランベルスクエア201',source:'kyotanba'},
      {time:'晚餐后 · 约 21:30',title:'京丹波 → 东京塔',status:'待定（拍照）',type:'交通',detail:'出租车约 10–20 分钟。',origin:'銀座やきとり 京丹波 東京都中央区銀座7-2-18 銀座グランベルスクエア201',place:'Tokyo Tower',travelMode:'driving'},
      {time:'约 22:00',title:'东京塔夜景 · 芝公园 / 赤羽桥',status:'拟定',type:'景点',detail:'主展望台 09:00–23:00，最晚 22:30 入场；顶部展望台至 22:45，最晚 22:15 入场。外观亮灯通常至 24:00；是否登塔待定。',place:'Tokyo Tower',places:['Tokyo Tower','Shiba Park Tokyo','Akabanebashi Station Tokyo'],source:'tower',extraSource:'towerLights'}],meals:{breakfast:'筑地海鲜早餐',lunch:'浅草寺商业街小吃',dinner:'19:30 银座京丹波 · 两人吧台 · 季节限定套餐 · 已预订'},todo:['确定东京塔是否登塔']},
    {date:'2026-10-13',city:'京都',group:'京都',title:'去京都，走进岚山小路',subtitle:'先寄存行李，再从奥嵯峨往回慢慢走。',hotel:'kyoto',tags:['东京 → 京都','京都第 1 晚'],versionConflict:true,route:['东京站','京都三条酒店','爱宕念佛寺','奥嵯峨','岚山'],events:[
      {time:'约 08 点',title:'东京退房 → 新干线到京都',status:'待购票',type:'交通',detail:'计划乘 8 点多的新干线，车次待定；出发前退房。东京 → 京都约 2.5 小时。',origin:'Tokyo Station',place:'Kyoto Station'},
      {time:'抵达后',title:'京都站 → 酒店，询问寄存行李',status:'建议',type:'住宿',detail:'地铁乌丸线到乌丸御池，5 号出口步行约 3 分钟。酒店 15:00 起入住；寄存与提前入住需前台确认。',source:'kyoto',hotel:'kyoto'},
      {time:'下午',title:'爱宕念佛寺 → 奥嵯峨 → 岚山',status:'拟定',type:'景点',detail:'初稿考虑从酒店打车至爱宕念佛寺，再依次往山下走。抵达、午饭和车程会压缩下午游玩时间，开闭门时间与取舍待核实。',places:['Otagi Nenbutsuji Kyoto','Saga Toriimoto Kyoto','Gio-ji Kyoto','Jojakko-ji Kyoto','Arashiyama Bamboo Forest Kyoto','Tenryu-ji Kyoto','Togetsukyo Bridge Kyoto']},
      {time:'傍晚 / 晚上',title:'回酒店入住，三条周边吃晚饭',status:'待定',type:'餐饮',detail:'Obanzai / 京料理 + 清酒；餐厅待定。'}],meals:{lunch:'酒店附近 · 待定',dinner:'Obanzai / 京料理 + 清酒 · 待定'},todo:['确定京都路线版本','购买东京 → 京都新干线车票'],alternative:'原 PDF：寄存行李后去二条城 → 锦市场 → 寺町通 → 河原町 → 鸭川 / 先斗町；岚山安排在 10/15。'},
    {date:'2026-10-14',city:'京都',group:'京都',title:'千本鸟居，东山与祇园',subtitle:'京都的经典街景，留时间慢逛。',hotel:'kyoto',tags:['伏见稻荷与东山','京都第 2 晚'],route:['伏见稻荷','清水寺','二年坂 / 三年坂','祇园'],events:[
      {time:'上午',title:'伏见稻荷 · 千本鸟居',status:'拟定',type:'景点',detail:'先走千本鸟居核心段，建议上午较早出发；攀登范围和出门时间待定。',place:'Fushimi Inari Taisha Kyoto'},
      {time:'中午 / 下午',title:'清水寺 → 三年坂 → 二年坂',status:'拟定',type:'景点',detail:'伏见稻荷 → 清水寺拟打车；东山步行游逛。',places:['Kiyomizu-dera Kyoto','Sannenzaka Kyoto','Ninenzaka Kyoto']},
      {time:'下午',title:'八坂塔 → 八坂神社 → 祇园',status:'拟定',type:'游逛',detail:'花见小路、祇园白川与周边小店，慢逛街景。',places:['Yasaka Pagoda Kyoto','Yasaka Shrine Kyoto','Hanamikoji Kyoto','Gion Shirakawa Kyoto']},
      {time:'晚上',title:'怀石料理晚餐',status:'待预约',type:'餐饮',detail:'期望米其林怀石料理；餐厅与席位均未确定。'}],meals:{lunch:'待定',dinner:'怀石料理 · 待预约'},todo:['预约怀石料理晚餐']},
    {date:'2026-10-15',city:'京都',group:'京都',title:'抹茶宇治，与奈良的鹿',subtitle:'离开市区一天，晚上回京都。',hotel:'kyoto',tags:['宇治 + 奈良','京都第 3 晚'],versionConflict:true,route:['京都','宇治','奈良','京都'],events:[
      {time:'上午',title:'京都 → 宇治：平等院与茶店',status:'拟定',type:'景点',detail:'初稿以 JR 为主。平等院、宇治川、抹茶和小街；出发时间、车次与入场票待定。',places:['Byodo-in Uji','Uji River Kyoto']},
      {time:'下午',title:'宇治 → 奈良：奈良公园与东大寺',status:'拟定',type:'景点',detail:'以 JR 为主，具体换乘和时长待补充。奈良町为时间允许时的备选。',places:['Nara Park','Todai-ji Nara','Naramachi Nara']},
      {time:'晚上',title:'返回京都 · 和牛晚餐',status:'待预约',type:'餐饮',detail:'顶级和牛烧肉 / 肉割烹，餐厅与时间待定。'}],meals:{lunch:'待定',dinner:'和牛烧肉 / 肉割烹 · 待预约'},todo:['预约和牛晚餐'],alternative:'原 PDF：爱宕念佛寺 → 奥嵯峨 → 祇王寺 → 常寂光寺 → 竹林小径 → 天龙寺 → 渡月桥；傍晚回三条通、寺町。'},
    {date:'2026-10-16',city:'大阪',group:'大阪',title:'到大阪，逛到道顿堀',subtitle:'把行李放在梅田，去大阪南区。',hotel:'osaka',tags:['京都 → 大阪','大阪第 1 晚'],route:['梅田酒店','通天阁','难波八阪神社','堀江','心斋桥','道顿堀'],events:[
      {time:'上午',title:'京都退房 → 大阪梅田',status:'建议',type:'交通',detail:'京都酒店最晚 12:00 退房，计划上午先出发。可乘 JR 京都线至大阪站；车次和门到门时长待确定。',origin:'Kyoto Station',place:'Osaka Station',source:'jr'},
      {time:'抵达后',title:'酒店询问寄存行李',status:'建议',type:'住宿',detail:'JR 大阪站连络桥出口步行约 3 分钟，大堂在 9 楼。15:00 起入住，先向前台询问寄存。',source:'osaka',hotel:'osaka'},
      {time:'中午 / 下午',title:'通天阁 → 难波八阪神社 → 堀江',status:'拟定',type:'游逛',detail:'午餐尚未确定；堀江 / Orange Street 逛小店。通天阁是否登塔待定。',places:['Tsutenkaku Osaka','Namba Yasaka Shrine Osaka','Orange Street Osaka']},
      {time:'傍晚 / 晚上',title:'心斋桥 → 道顿堀 · 蟹料理',status:'待定',type:'游逛',detail:'购物、街景与高级蟹料理晚餐，餐厅尚未预约。之后回梅田酒店办理入住。',places:['Shinsaibashi Osaka','Dotonbori Osaka']}],meals:{lunch:'待定',dinner:'高级蟹料理 · 待预约'},todo:['预约蟹料理晚餐']},
    {date:'2026-10-17',city:'大阪',group:'大阪',title:'大阪城与梅田购物日',subtitle:'上午看看城，下午留给购物。',hotel:'osaka',tags:['大阪城 + 梅田','大阪第 2 晚'],route:['大阪城','梅田','阪急 / 阪神','LUCUA','Grand Front'],events:[
      {time:'上午',title:'大阪城公园、护城河与外观',status:'拟定',type:'景点',detail:'大阪城外观、公园与护城河；天守阁入场待定。',place:'Osaka Castle'},
      {time:'下午',title:'梅田购物',status:'拟定',type:'购物',detail:'阪急、阪神、LUCUA、Grand Front、Osaka Station City，具体购物清单后续补充。',places:['Hankyu Umeda Main Store Osaka','Hanshin Umeda Main Store Osaka','LUCUA Osaka','Grand Front Osaka']},
      {time:'晚上',title:'居酒屋晚餐，整理行李',status:'待定',type:'餐饮',detail:'餐厅待定；饭后整理行李。'}],meals:{lunch:'待定',dinner:'居酒屋 · 餐厅待定'},todo:[]},
    {date:'2026-10-18',city:'离境',group:'大阪',title:'从关西机场，各自回家',subtitle:'北京与上海，两班航班从 T1 出发。',hotel:null,checkoutHotel:'osaka',tags:['14:00 北京','14:20 上海'],route:['梅田酒店','大阪站','关西机场 T1','北京 / 上海'],events:[
      {time:'早上',title:'早餐，取行李并提前退房',status:'建议',type:'住宿',detail:'大阪酒店最晚 12:00 退房，但应按机场计划提前离开。只安排附近早餐，最后补买视时间决定。',hotel:'osaka'},
      {time:'约 09:15–09:30',title:'从酒店前往关西机场',status:'建议',type:'交通',detail:'目标在约 11:00 抵达 KIX T1，给较早的北京航班预留 3 小时。可选 JR HARUKA：大阪站到机场官方参考约 47 分钟，再加步行、等车和找航站楼，门到门先留 80–100 分钟。建议出发时段，未锁定具体班次。',steps:['退房后，打开大阪站 Umekita 地下入口导航，酒店至地下出口参考步行约 6 分钟。','查好开往关西机场的 HARUKA 班次并购买车票，给站内步行与找站台留时间。','关西机场站下车后，跟随 Terminal 1 / International Departures 标志。','北京和上海航班分别办理值机与托运，核对当天柜台和登机口。'],origin:'Hotel Hankyu RESPIRE OSAKA',place:'Kansai International Airport Terminal 1',source:'osaka'},
      {time:'14:00',title:'CA928 · 大阪 → 北京',status:'已预订',type:'航班',detail:'KIX T1 起飞，北京当地时间 16:30 抵达 PEK T3。',flight:'beijing'},
      {time:'14:20',title:'MU516 · 大阪 → 上海',status:'已预订',type:'航班',detail:'KIX T1 起飞，上海当地时间 16:10 抵达 PVG T1。',flight:'shanghai'}],meals:{lunch:'机场 / 机上用餐',dinner:'抵达后自行安排'},todo:['确定机场交通班次']}
  ]
};
